In [1]:
import numpy as np

In [3]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [4]:
np.ones((7,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [8]:
arr = np.arange(3,5)

In [9]:
arr

array([3, 4])

In [10]:
arr[0]

3

In [17]:
arr = np.random.randint(-10,150,15)

In [18]:
arr.reshape((3,5))

array([[ 72, 127,  14,  62,  38],
       [ 51,   0, 104, 136,  33],
       [ 55,  76, 136, 112, 113]])

In [20]:
arr.shape

(15,)